### ISSUE TITLE
PROJECT CHECKLIST

### ISSUE THREAD

**Issue by n8willis** [batsimadz/Sankofa-Display#13]
_This issue tracks checkpoints for the project long term and will be updated by reviewers and QA_

## MILESTONE 1

- [x] Concept for design
- [x] Contract Signing
- [x] GitHub setup complete
- [x] PROTOTYPE HamburgefontsivHAMBURGEFONTSIV!., “space char”
- [x] GoogleFonts Project Template
- [x] Font Building and producing artifacts in Actions tab?
- [x] Checking Fontbakery fails?
- [x] Checking glyph coverage for milestone?

- [x] Team members and reviewers added as collaborators in the repo

### Path direction correction

- [x] Are all characters interpolating? Select all in font tab and fix path direction shift+command+R

### Not necessary in Repo but good for reviewers

- [x] Proofing with Font Proofer or similar tools.
- [x] Are proofs of all characters made? Do you have text set in the font? Are you printing and proofing?
- [x] Are proofs being sent to reviewers for feedback?

### Spacing

- [x] Spacing is tested with spacing strings
- [x] Capitals are spaced to work with lowercase letters

## MILESTONE 2

- [x] 53+ glyphs
- [x] Font Building and producing artifacts in Actions tab?
- [x] Checking Fontbakery fails?

### Path direction correction

- [x] Are all characters interpolating? Select all in font tab and fix path direction shift+command+R

### Not necessary in Repo but good for reviewers

- [x] Proofing with Font Proofer or similar tools.
- [x] Are proofs of all characters made? Do you have text set in the font? Are you printing and proofing?
- [x] Proofs are made with randomized text, and tested at the range of sizes defined in the project brief
- [x] Are proofs being sent to reviewers for feedback?

## MILESTONE 3

- [x] 80+ characters incl. A-Z, a-z, 0-9 in font
- [x] Diacritics (in sets of western euro, Vietnamese, floating, attached)
- [x] Special SSA characters/ Diacritics
- [x] Diacritics are built from combining forms + anchor points
- [ ] Diacritics fit into vertical metrics
- [x] Font Building and producing artifacts in Actions tab?
- [x] Checking Fontbakery fails?

### Path direction correction

- [x] Are all characters interpolating? Select all in font tab and fix path direction shift+command+R
- [ ] Are all overlaid diacritics using the same path direction?

### Spacing

- [x] Numerals are tabular spaced 

### Not necessary in Repo but good for reviewers

- [x] Proofing with Font Proofer or similar tools.
- [x] Are proofs of all characters made? Do you have text set in the font? Are you printing and proofing?

## MILESTONE 4

- [x] SSA Google charset ~560 characters x variation axes
- [x] Font Building and producing artifacts in Actions tab?
- [x] Checking Fontbakery fails?

### Path direction correction

- [ ] Are all characters interpolating? Select all in font tab and fix path direction shift+command+R

### Spacing

- [ ] Kerning with Kern On and reviewing kerning (lowercase-lowercase, Capital-lowercase, numerals)

### Not necessary in Repo but good for reviewers

- [x] Proofing with Font Proofer or similar tools.
- [x] Are proofs of all characters made? Do you have text set in the font? Are you printing and proofing?

## MILESTONE 5

- [ ] Additional fixing?
- [ ] Fontbakery Bug Fixes
- [ ] Font Building and producing artifacts in Actions tab?
- [ ] Checking Fontbakery fails?

- [ ] Variable axes build?

- [ ] OpenType smart-font features build?

## MILESTONE 6

- [ ] All glyphs complete and known bugs fixed
- [ ] Review with onboarding team

## MILESTONE 7

- [ ] Social media promotion, additional static and animated assets
produced, print-on-demand merchandise available

- [ ] Pull request to Google fonts made? Add font issue to google fonts filed?
